ALTER TABLE shipping_bookings
ADD COLUMN price_set TINYINT(11) DEFAULT 0,
ADD COLUMN hs_code VARCHAR(50) DEFAULT NULL,
ADD COLUMN declared_customs_value DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN declared_currency VARCHAR(10) DEFAULT NULL,
ADD COLUMN is_insured TINYINT(1) DEFAULT 0,
ADD COLUMN insured_amount DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN incoterms VARCHAR(20) DEFAULT NULL,
ADD COLUMN set_as_residential TINYINT(1) DEFAULT 0,
ADD COLUMN tax_duty DECIMAL(10,2) DEFAULT NULL;
